/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#00216e",
        "primary-container": "#0033a0",
        "on-primary": "#ffffff",
        "on-primary-container": "#8ea6ff",
        "on-primary-fixed": "#001550",
        "on-primary-fixed-variant": "#133ca8",
        "primary-fixed": "#dce1ff",
        "primary-fixed-dim": "#b6c4ff",
        "inverse-primary": "#b6c4ff",
        
        "secondary": "#5e5e5d",
        "secondary-container": "#e0dfdd",
        "secondary-fixed": "#e3e2e0",
        "secondary-fixed-dim": "#c7c6c4",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#626361",
        "on-secondary-fixed": "#1b1c1b",
        "on-secondary-fixed-variant": "#464746",
        
        "tertiary": "#1c2b34",
        "tertiary-container": "#32414b",
        "tertiary-fixed": "#d5e5f1",
        "tertiary-fixed-dim": "#b9c9d5",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#9dadb9",
        "on-tertiary-fixed": "#0e1d26",
        "on-tertiary-fixed-variant": "#3a4953",
        
        "surface": "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#3456c1",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        
        "background": "#f8f9fa",
        "on-background": "#191c1d",
        "on-surface": "#191c1d",
        "on-surface-variant": "#444653",
        
        "outline": "#747684",
        "outline-variant": "#c4c5d5",
        "platinum": "#c4c5d5",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        "section-gap": "80px",
        gutter: "24px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "margin-desktop": "64px",
        "margin-mobile": "24px",
        "container-max": "1280px",
      },
      fontFamily: {
        "display-lg": ["var(--font-eb-garamond)", "serif"],
        "display-md": ["var(--font-eb-garamond)", "serif"],
        "headline-lg": ["var(--font-eb-garamond)", "serif"],
        "headline-lg-mobile": ["var(--font-eb-garamond)", "serif"],
        "headline-sm": ["var(--font-eb-garamond)", "serif"],
        "headline-md": ["var(--font-eb-garamond)", "serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
        "caption": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "500" }],
        "display-md": ["36px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-lg": ["30px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "caption": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
