/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#474747",
        "surface-tint": "#5e5e5e",
        "surface": "#f9f9f9",
        "inverse-on-surface": "#f0f1f1",
        "surface-container": "#eeeeee",
        "on-secondary-fixed": "#1b1c1b",
        "tertiary-fixed-dim": "#c7c6c6",
        "surface-container-highest": "#e2e2e2",
        "surface-bright": "#f9f9f9",
        "on-primary-container": "#848484",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#464747",
        "primary-container": "#1b1b1b",
        "on-surface": "#1a1c1c",
        "background": "#f9f9f9",
        "on-tertiary-fixed": "#1b1c1c",
        "secondary-fixed-dim": "#c7c6c4",
        "inverse-surface": "#2f3131",
        "on-secondary-container": "#626361",
        "surface-container-low": "#f3f3f4",
        "on-secondary-fixed-variant": "#464746",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-primary-fixed": "#1b1b1b",
        "primary-fixed": "#e2e2e2",
        "tertiary-fixed": "#e4e2e2",
        "tertiary-container": "#1b1c1c",
        "on-surface-variant": "#4c4546",
        "on-error": "#ffffff",
        "secondary": "#5e5e5d",
        "on-primary": "#ffffff",
        "outline": "#7e7576",
        "secondary-container": "#e0dfdd",
        "on-background": "#1a1c1c",
        "surface-dim": "#dadada",
        "inverse-primary": "#c6c6c6",
        "secondary-fixed": "#e3e2e0",
        "surface-variant": "#e2e2e2",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "outline-variant": "#cfc4c5",
        "tertiary": "#000000",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#848484",
        "surface-container-high": "#e8e8e8",
        "primary-fixed-dim": "#c6c6c6",
        "primary": "#000000",
        "charcoal": "#1a1c1c",
        "charcoal-dark": "#121110",
        "bronze-gold": "#7e7576",
        "bronze-light": "#a39b9c",
        "sand-50": "#f9f9f9",
        "sand-100": "#f3f3f4",
        "sand-200": "#e8e8e8",
        "platinum": "#E5E4E2",
        "burgundy": "#000000",
        "burgundy-light": "#2f3131",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "section-gap": "128px",
        "margin-desktop": "64px",
        unit: "8px",
        gutter: "32px",
        "container-max": "1360px",
        "margin-mobile": "24px",
      },
      fontFamily: {
        "body-md": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-sm": ["var(--font-eb-garamond)", "serif"],
        "display-lg": ["var(--font-eb-garamond)", "serif"],
        "headline-md": ["var(--font-eb-garamond)", "serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
        "display-lg-mobile": ["var(--font-eb-garamond)", "serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
